### PR TITLE
fixed empty apps list if no search string provided

### LINKED ISSUE #1047: Empty Apps list
When opening the "Apps" tab you currently see an empty apps list.

### PR DESCRIPTION
**Pull request by plata**
fixes #1047

### CODE REVIEW

**Comment by plata** [comment]
Not yet ;)

File: phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java [hunk 1]
```diff
@@ -26,6 +26,7 @@
 import javafx.event.EventHandler;
 import javafx.scene.input.MouseEvent;
 import me.xdrop.fuzzywuzzy.FuzzySearch;
+import org.eclipse.jgit.util.StringUtils;
```
Comment (madoar) [inline phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java]: Can you change this import to the apache dependency? I didn't even know that jgit contains such a method...

Comment (plata) [inline phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/ViewApps.java]: Too late, already merged. IntelliJ chose that one.
