### PR TITLE
fixed generic engines and engine tools

### LINKED ISSUE #1122: Nothing happen when clicking on a container
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at org.phoenicis.javafx.views.mainwindow.containers.ContainerPanelFactory.createContainerPanel(ContainerPanelFactory.java:52)
	at org.phoenicis.javafx.controller.containers.ContainersController.lambda$new$8(ContainersController.java:86)
	at org.phoenicis.javafx.views.mainwindow.containers.ContainersView.showContainerDetails(ContainersView.java:130)
	at org.phoenicis.javafx.views.mainwindow.containers.ContainersView.lambda$new$0(ContainersView.java:77)
	at org.phoenicis.javafx.views.common.widgets.lists.CombinedListWidget.lambda$new$0(CombinedListWidget.java:67)
	at org.phoenicis.javafx.views.common.widgets.lists.icons.IconsListWidget.lambda$null$0(IconsListWidget.java:84)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.phoenicis.javafx.views.mainwindow.containers.ContainerPanelFactory.createContainerPanel(ContainerPanelFactory.java:48)
	... 41 more
Caused by: java.lang.NullPointerException
	at org.phoenicis.javafx.views.mainwindow.containers.WinePrefixContainerWineToolsTab.populate(WinePrefixContainerWineToolsTab.java:61)
	at org.phoenicis.javafx.views.mainwindow.containers.WinePrefixContainerWineToolsTab.<init>(WinePrefixContainerWineToolsTab.java:47)
	at org.phoenicis.javafx.views.mainwindow.containers.WinePrefixContainerPanel.<init>(WinePrefixContainerPanel.java:47)
	... 46 more
`

### PR DESCRIPTION
**Pull request by plata**
Fixes the problem that engine tools and engines could not be loaded if "Engines" was translated. Also: if no engine tools are available, the "Engine tools" tab in the container view is not shown.

fixes #1122

### CODE REVIEW

File: phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerWineToolsTab.java [hunk 1]
```diff
@@ -51,6 +51,10 @@ private void populate(ApplicationDTO engineTools) {
         final VBox toolsPane = new VBox();
         final Text title = new TextWithStyle(tr("Wine tools"), TITLE_CSS_CLASS);
 
+        if (engineTools == null) {
+            return;
```
Comment (madoar) [inline phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerWineToolsTab.java]: Just asking:
Should this happen, that null is passed?
If this is the case I think we should think about passing an `Optional` object to the method.

Comment (plata) [reply phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerWineToolsTab.java]: It depends on the repository really. It might be that you do not have engine tools in your scripts. I'm currently not quite sure which is the best place to check this. So at the moment, this is only a safety guard to avoid a crash in case this happens.

Comment (madoar) [reply phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerWineToolsTab.java]: Then I think we should add a `TODO: check later if null should really happen`.

Comment (plata) [reply phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerWineToolsTab.java]: I will implement a solution.

File: phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerPanel.java [hunk 2]
```diff
@@ -37,19 +38,24 @@
...
 
         this.informationTab = new WinePrefixContainerInformationTab(containerEntity, engineVersions);
+        this.tabPane.getTabs().add(this.informationTab);
         this.displayTab = new WinePrefixContainerDisplayTab(containerEntity, winePrefixContainerController);
+        this.tabPane.getTabs().add(this.displayTab);
         this.inputTab = new WinePrefixContainerInputTab(containerEntity);
-        this.wineToolsTab = new WinePrefixContainerWineToolsTab(containerEntity, winePrefixContainerController,
-                engineToolsManager, engineTools);
+        this.tabPane.getTabs().add(this.inputTab);
+        if (engineTools.isPresent()) {
```
Comment (madoar) [inline phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerPanel.java]: Maybe we can add a panel with a message like "no engine tools available" in case no repository is found?

Comment (plata) [reply phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerPanel.java]: I don't know if this makes sense because as a user, there's nothing you could do about it. So what are you supposed to do if you see that message?

Comment (madoar) [reply phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/containers/WinePrefixContainerPanel.java]: I've misread. I thought you always add the tab.
