### PR TITLE
fixed handling of FailurePanel

### LINKED ISSUE #740: Show error message when something during the repository fetching goes wrong
We need a pop-up when something goes wrong while fetching the repository. This pop-up should then show the problem. Could be several things:

- no Internet connection
- folder does not exist
- folder is not a git repository
- ...

See #663 for more context information

### PR DESCRIPTION
**Pull request by plata**
set notification and failure reason whenever FailurePanel is shown

fixes #740

failure panel

### CODE REVIEW

File: phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java [hunk 1]
```diff
@@ -64,7 +65,7 @@ public EnginesController(ViewEngines viewEngines, RepositoryManager repositoryMa
         this.themeManager = themeManager;
 
         this.repositoryManager.addCallbacks(this::populateView,
-                e -> Platform.runLater(() -> viewEngines.showFailure()));
+                e -> Platform.runLater(() -> viewEngines.showFailure(tr("Loading engines failed."), Optional.of(e))));
```
Comment (madoar) [inline phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java]: Just asking:
Am I overlooking something or are you always using `Optional.of(e)`? If this is the case why are we using an `Optional`, `Optional.of(null)` will throw an error?

Comment (plata) [inline phoenicis-javafx/src/main/java/org/phoenicis/javafx/controller/engines/EnginesController.java]: Yes, I'm currently using `Optional.of(e)` everywhere. However, I wanted to have the possibility to call it with `Optional.empty()`. It might happen that you want to show a `FailurePanel` but do not have an exception.
